import { Router, type IRouter } from "express";
import healthRouter from "./health";
import regionRouter from "./region";
import authRouter from "./auth";
import authSocialRouter from "./auth-social";
import profileRouter from "./profile";
import onboardingRouter from "./onboarding";
import accountsRouter from "./accounts";
import categoriesRouter from "./categories";
import commitmentsRouter from "./commitments";
import transactionsRouter from "./transactions";
import budgetsRouter from "./budgets";
import debtsRouter from "./debts";
import insightsRouter from "./insights";
import dashboardRouter from "./dashboard";
import uploadsRouter from "./uploads";
import gamificationRouter from "./gamification";
import goalsRouter from "./goals";
import netWorthRouter from "./net-worth";
import assetsRouter from "./assets";
import receiptRouter from "./receipt";
import storageRouter from "./storage";
import agentRouter from "./agent";
import paydayPromptRouter from "./payday-prompt";
import feedbackRouter from "./feedback";
import incomeSourcesRouter from "./income-sources";
import adminSeedRouter from "./admin-seed";

const router: IRouter = Router();

router.use(healthRouter);
router.use(regionRouter);
router.use(authRouter);
router.use(authSocialRouter);
router.use(profileRouter);
router.use(onboardingRouter);
router.use(accountsRouter);
router.use(categoriesRouter);
router.use(commitmentsRouter);
router.use(transactionsRouter);
router.use(budgetsRouter);
router.use(debtsRouter);
router.use(insightsRouter);
router.use(dashboardRouter);
router.use(uploadsRouter);
router.use(gamificationRouter);
router.use(goalsRouter);
router.use(netWorthRouter);
router.use(assetsRouter);
router.use(receiptRouter);
router.use(storageRouter);
router.use(agentRouter);
router.use(paydayPromptRouter);
router.use(feedbackRouter);
router.use(incomeSourcesRouter);
router.use(adminSeedRouter);

export default router;
