// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cashflow-layouts/CommandCenter.tsx": () => import("../components/mockups/cashflow-layouts/CommandCenter.tsx"),
  "./components/mockups/cashflow-layouts/CompactTable.tsx": () => import("../components/mockups/cashflow-layouts/CompactTable.tsx"),
  "./components/mockups/cashflow-layouts/WaterfallFlow.tsx": () => import("../components/mockups/cashflow-layouts/WaterfallFlow.tsx")
};
